name: hisabone
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  http: ^1.2.0
  syncfusion_flutter_datagrid: ^24.1.41
  shared_preferences: ^2.2.2
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.1.0
  fpdart: ^1.1.1
  meta: ^1.16.0
  intl: ^0.18.1
  data_table_2: ^2.5.10
  sticky_headers: ^0.3.0
  carousel_slider: ^5.0.0
  flutter_native_splash: ^2.4.1
  firebase_core: ^3.10.0
  firebase_messaging: ^15.1.3
  grouped_list: ^5.1.2


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_apk1.png"
  min_sdk_android: 21  

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#05A3F9" # background color
  image: assets/images/logo_apk1.png # logo kamu
  android: true
  ios: true
  web: false

